config/routes.rb
Rails.application.routes.draw do
  resources :trades, except: [:edit, :update] do
    resources :participants, only: [:create, :edit, :update]
  end

  resources :users, only: [:index, :show, :create] do
    resources :participants, only: [:index]
  end

  resources :moderators, only: [:index] 
  get 'moderators/import_trades', to: "moderators#import_trades"
  get 'moderators/change_username', to: "moderators#change_username"
  get 'moderators/add_trade', to: "moderators#add_trade"

  resources :help, only: [:index]

  resources :sessions, only: [:new, :destroy]
  get '/auth/:provider/callback', to: 'sessions#create', as: :oauth_callback

  root to: 'trades#index'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  paginates_per 5

  belongs_to :user
  belongs_to :trade

  validates :user,      presence: true
  validates :message,   presence: true
  validates :trade,     presence: true
  validates :hashcode,  presence: true, uniqueness: true

  scope :unseen,    ->{ where("seen_at IS NULL") }

  before_validation :create_hashcode


  def seen?
    seen_at?
  end


  def mark_as_seen!
    update_attributes(seen_at: Time.now)
  end

  
  def self.updated_shipping(participant)
    participant.other_participants.each do |p|
      if_not_already_sent do
        n = Notification.create!(user: p.user, 
                             message: "#{participant.user} has shipped",
                             trade: p.trade)

        Reddit.pm(p.user.username, "#{participant.user} has shipped", 
                  'notifications/updated_shipping', 
                  participant: participant, notification: n)
      end
    end
  end


  def self.send_invites(participants)
    participants.each do |p|
      if_not_already_sent do
        n = Notification.create!(user: p.user, 
                             message: "you have been invited to a trade",
                             trade: p.trade)

        Reddit.pm(p.user.username, "/r/beertrade trade invite", 
                  'notifications/invite', 
                  participant: p, notification: n)
      end
    end
  end


  def self.left_feedback(participant)
    if_not_already_sent do
      other_username = participant.other_participant.user.to_s

      n = Notification.create!(user: participant.user, 
                           message: "#{other_username} has left you feedback",
                           trade: participant.trade)

      Reddit.pm(participant.user.username, "#{other_username} has left you feedback", 
                "notifications/left_feedback", 
                participant: participant, notification: n)
    end
  end


  def self.accepted_trade(participant)
    participant.other_participants.each do |p|
      if_not_already_sent do
        n = Notification.create!(user: p.user, 
                                 message: "#{participant.user} has accepted your trade request",
                                 trade: participant.trade)

        Reddit.pm(p.user.username, "#{participant.user} has accepted your trade request", 
                  "notifications/trade_accepted", 
                  participant: p, other_participant: participant, notification: n)
      end
    end
  end


  private

    def self.if_not_already_sent
      Notification.transaction do
        begin
          yield
        rescue ActiveRecord::RecordInvalid => e
          raise unless e.record.errors.messages.include?(:hashcode)
        end
      end
    end

    def create_hashcode
      return unless user
      self.hashcode = Digest::SHA1.hexdigest(user.id.to_s << message << trade.id.to_s)
    end
end

app/views/notifications/_bad_trade_reported.md.erb
hi, we're writing to let you know that a bad trade has been reported for <%= participant.user %>.  please review and manually approve if this is the appropriate action:

<%= edit_trade_participant_url(participant.trade, participant) %>

app/views/notifications/_invite.md.erb
hi <%= participant.user %>, we're messaging you to let you know that <%= participant.other_participant.user %> has a requested a trade with you via the /r/beertrade subreddit. 

<% if participant.trade.agreement? %>
  **the agreed trade was**: <%= participant.trade.agreement %>
<% end %>

to confirm this trade please visit this link: <%= trade_url(participant.trade, notification_id: notification.id) %>

once you and <%= participant.other_participant.user %> have completed your trade, go back to the link above and leave them feedback to close the trade out

app/views/notifications/_left_feedback.md.erb
hi, wanted to let you know that <%= participant.other_participant.user %> has left <%= participant.feedback_type %> feedback for you:

<%= trade_url(participant.trade, notification_id: notification.id) %>

app/views/notifications/_notification.html.erb
<li class="unseen-notification'">
  <%= link_to notification.message, trade_path(id: notification.trade, notification_id: notification.id) %>
</li>

app/views/notifications/_show.html.erb
<li class='<%= notification.seen? ? 'seen-notification' : 'unseen-notification' %>'>
  <%= link_to notification.message, trade_path(notification.trade, notification_id: notification.id) %>
</li>

app/views/notifications/_trade_accepted.md.erb
congrats, <%= other_participant.user %> has accepted your trade request: [<%= participant.trade %>](<%= trade_url(participant.trade) %>)

app/views/notifications/_updated_shipping.md.erb
hi, just wanted to let you know that <%= participant.user %> has shipped your box. here is the tracking number: <%= participant.shipping_info %>