config/routes.rb
Rails.application.routes.draw do
  resources :trades, except: [:edit, :update] do
    resources :participants, only: [:create, :edit, :update]
  end

  resources :users, only: [:index, :show, :create] do
    resources :participants, only: [:index]
  end

  resources :moderators, only: [:index] 
  get 'moderators/import_trades', to: "moderators#import_trades"
  get 'moderators/change_username', to: "moderators#change_username"
  get 'moderators/add_trade', to: "moderators#add_trade"

  resources :help, only: [:index]

  resources :sessions, only: [:new, :destroy]
  get '/auth/:provider/callback', to: 'sessions#create', as: :oauth_callback

  root to: 'trades#index'
end

app/controllers/moderators_controller.rb
class ModeratorsController < ApplicationController
  before_filter :requires_moderator!

  def index
    @mod_pending_trades = Trade.joins(:participants).merge(Participant.needing_moderator_approval).page(params[:mod_pending_page])
    @not_accepted_trades = Trade.joins(:participants).merge(Participant.old_and_not_yet_accepted).page(params[:not_accepted_page])
  end
end

app/views/moderators/_navigation.html.erb
<nav>
  <ul class="nav nav-tabs">
    <li role="presentation" class="<%= 'active' if active == :index %>"><a href="<%= moderators_path %>">trades waiting feedback</a></li>
    <li role="presentation" class="<%= 'active' if active == :import_trades %>"><a href="<%= moderators_import_trades_path %>">import trades</a></li>
    <li role="presentation" class="<%= 'active' if active == :ban_user %>"><a href="<%= moderators_ban_user_path %>">ban user</a></li>
    <li role="presentation" class="<%= 'active' if active == :change_username %>"><a href="<%= moderators_change_username_path %>">change username</a></li>
    <li role="presentation" class="<%= 'active' if active == :add_trade %>"><a href="<%= moderators_add_trade_path %>">add a trade</a></li>
  </ul>
</nav>

app/views/moderators/add_trade.html.erb
<%= render "navigation", active: :add_trade %>

<h2>add a trade</h2>


<%= form_for Trade.new do |f| %>
  <div class="form-group">
    <%= f.label :agreement, "what did they agree to trade?", class: "control-label" %>
    <%= f.text_field :agreement, placeholder: "(optional)", class: "form-control" %>
  </div>


  <h3>reddit user and the feedback they gave</h3>

  <%= fields_for User.new do |u| %>
    <div class="form-group has-feedback">
      <%= u.label :username, "username:", class: "control-label" %>
      <%= render "users/reddit_user_search", {username_field: "user[username]", hide_validation: true} %>
    </div>
  <% end %>

  <%= fields_for Participant.new do |p| %>
    <div class="form-group">
      <%= p.radio_button :feedback_type, 'positive', checked: true %>
      <%= p.label :feedback_type, 'positive', value: 'positive' %>

      <%= p.radio_button :feedback_type, 'neutral' %>
      <%= p.label :feedback_type, 'neutral', value: 'neutral' %>

      <%= p.radio_button :feedback_type, 'negative' %>
      <%= p.label :feedback_type, 'negative', value: 'negative' %>
    </div>

    <div class="form-group">
      <%= p.label :feedback, "feedback", class: "control-label" %>
      <%= p.text_area :feedback, maxlength: 1000, class: "form-control" %>
    </div>
  <% end %>



  <h3>other reddit user and the feedback they gave</h3>

  <%= fields_for :other_user, User.new do |u| %>
    <div class="form-group has-feedback">
      <%= u.label :username, "username:", class: "control-label" %>
      <%= render "users/reddit_user_search", {username_field: "other_user[username]", hide_validation: true} %>
    </div>
  <% end %>

  <%= fields_for :other_participant, Participant.new do |p| %>
    <div class="form-group">
      <%= p.radio_button :feedback_type, 'positive', checked: true %>
      <%= p.label :feedback_type, 'positive', value: 'positive' %>

      <%= p.radio_button :feedback_type, 'neutral' %>
      <%= p.label :feedback_type, 'neutral', value: 'neutral' %>

      <%= p.radio_button :feedback_type, 'negative' %>
      <%= p.label :feedback_type, 'negative', value: 'negative' %>
    </div>

    <div class="form-group">
      <%= p.label :feedback, "feedback", class: "control-label" %>
      <%= p.text_area :feedback, maxlength: 1000, class: "form-control" %>
    </div>
  <% end %>


  <%= f.submit "add trade", class: "btn btn-primary" %>
<% end %>

app/views/moderators/change_username.html.erb
<%= render "navigation", active: :change_username %>

<h2>change username</h2>

<p>this will carry over the trades from the old username to the new one. note that this will remove the trades from the old user</p>

<%= form_for(User.new) do |f| %>
  <div class="form-group has-feedback">
    <%= f.label :username, "old reddit username:", class: "control-label" %>
    <%= render "users/reddit_user_search", {username_field: "user[username]", hide_validation: true} %>
  </div>

  <div class="reddit-username-input form-group has-feedback">
    <%= f.label :new_username, "new reddit username:", class: "control-label" %>
    <%= render "users/reddit_user_search", {username_field: "user[new_username]"} %>
  </div>

  <%= f.submit "import trades", class: "btn btn-primary" %>
<% end %>

app/views/moderators/import_trades.html.erb
<%= render "navigation", active: :import_trades %>

<h2>bulk import trades for a user</h2>

<%= form_for(Trade.new) do |f| %>
  <div class="reddit-username-input form-group has-feedback">
    <%= f.label :participant_username, "reddit username that we're importing trades for:", class: "control-label" %>
    <%= render "users/reddit_user_search" %>
  </div>

  <div class="form-group">
    <%= f.label :users_to_import, "list of reddit usernames they traded with:", class: "control-label" %>
    <%= text_area_tag :users_to_import, "", class: "form-control" %>
  </div>

  <%= f.submit "import trades", class: "btn btn-primary" %>
<% end %>

app/views/moderators/index.html.erb
<%= render "navigation", active: :index %>

<h3>trades with negative feedback which need mod approval</h3>

<%= render "trades/trade_list", trades: @mod_pending_trades, pagination_param: :mod_pending_page %>


<h3>trades which haven't been accepted by both parties</h3>

<%= render "trades/trade_list", trades: @not_accepted_trades, pagination_param: :not_accepted_page %>