config/routes.rb
Rails.application.routes.draw do
  resources :trades, except: [:edit, :update] do
    resources :participants, only: [:create, :edit, :update]
  end

  resources :users, only: [:index, :show, :create] do
    resources :participants, only: [:index]
  end

  resources :moderators, only: [:index] 
  get 'moderators/import_trades', to: "moderators#import_trades"
  get 'moderators/change_username', to: "moderators#change_username"
  get 'moderators/add_trade', to: "moderators#add_trade"

  resources :help, only: [:index]

  resources :sessions, only: [:new, :destroy]
  get '/auth/:provider/callback', to: 'sessions#create', as: :oauth_callback

  root to: 'trades#index'
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  paginates_per 15

  has_many :participants, dependent: :destroy
  has_many :users, through: :participants
  has_many :notifications, dependent: :destroy

  scope :completed,            ->{ where("completed_at IS NOT NULL").includes(:participants).includes(:users).order(completed_at: :desc) }
  scope :not_completed_yet,    ->{ where(completed_at: nil).includes(:participants).includes(:users).order(created_at: :desc) }
  scope :needing_mod_approval, ->{ where(completed_at: nil).includes(:participants).includes(:users).order(created_at: :desc) }


  def lowest_feedback
    participants.min_by {|p| p.feedback_type.to_i }.feedback_type 
  end

  def can_see?(user)
    accepted? || !participant(user).nil? || (user && user.moderator?)
  end

  def completed?
    completed_at?
  end

  def all_feedback_given?
    !participants.empty? && participants.pending.empty?
  end

  def has_shipping_info?
    !participants.empty? && participants.with_shipping_info.exists?
  end

  def accepted?
    !participants.empty? && !participants.not_yet_accepted.exists?
  end

  def waiting_to_give_feedback?(user)
    accepted? and p = self.participant(user) and p.waiting_to_give_feedback?
  end

  def can_delete?(user)
    waiting_for_approval?(user) || user.moderator?
  end

  def waiting_for_approval?(user)
    participant = participant(user)
    return false unless participant
    !participant.accepted?
  end


  def participant(user)
    return nil if user.nil?
    participants.find_by(user_id: user.id)
  end


  def organizing_participant
    participants.order(accepted_at: :asc).first
  end


  def create_participants(organizer_user, participant_reddit_username, ip_address)
    if organizer_user.username.downcase == participant_reddit_username.downcase
      self.errors.add(:base, "You cannot request a trade with yourself")
      raise ActiveRecord::RecordInvalid.new(self)
    end

    participants.build(user: organizer_user, accepted_at: Time.now, ip_address: ip_address)
    
    user = User.find_or_create_by_username(participant_reddit_username)

    to_invite = participants.build(user: user)
    save!

    to_invite
  rescue ActiveRecord::RecordInvalid 
    false
  end


  def to_s
    if !agreement.blank?
      agreement 
    else
      "trade on #{created_at.strftime("%m/%d/%Y")}"
    end
  end
end

app/controllers/trades_controller.rb
require 'moderator_tools'

class TradesController < ApplicationController
  before_filter :requires_authentication!, except: [:index, :show]


  def new
    @trade = Trade.new
  end


  def index
    @trades = Trade.completed
    @trades = @trades.basic_search(agreement: params[:q]) unless params[:q].blank?
    @trades = @trades.order(created_at: :desc).page(params[:page])
  end


  def show
    @trade = Trade.find(params[:id])

    if params[:notification_id]
      notification = @trade.notifications.find_by(id: params[:notification_id])
      notification.mark_as_seen! if notification && notification.user == current_user
    end

    if !@trade.can_see?(current_user)
      if current_user
        render_forbidden!
      else
        requires_authentication!
      end
    end
  end


  def create
    return trade_import if current_user.moderator? && params[:users_to_import]
    return add_trade if current_user.moderator? && params[:user] and params[:other_user]

    @trade = Trade.new(trade_params)

    username = params[:participant_username].strip
    if new_participant = @trade.create_participants(current_user, username, request.remote_ip)
      TradeInviteJob.perform_later(new_participant.id)

      flash[:notice] = "trade successfully requested.  waiting on #{new_participant.user} to confirm it"
      redirect_to current_user
    else
      flash[:alert] = @trade.errors.full_messages.first
      render :new
    end
  end


  def destroy
    @trade = Trade.find(params[:id])

    return render_forbidden! unless @trade.can_delete?(current_user)

    @trade.destroy

    flash[:notice] = "trade cancelled"
    redirect_to user_path(current_user)
  end


  private


    def trade_params
      params.require(:trade).permit(:agreement)
    end

    def user_params
      params.require(:user).permit(:username)
    end

    def other_user_params
      params.require(:other_user).permit(:username)
    end

    def participant_params
      params.require(:participant).permit(:feedback_type, :feedback)
    end

    def other_participant_params
      params.require(:other_participant).permit(:feedback_type, :feedback)
    end


    def trade_import
      user = User.find_by_username(params[:participant_username])

      if !user
        flash[:alert] = "user not found"
      elsif ModeratorTools.import_trades_for_user(user, params[:users_to_import])
        flash[:notice] = "successfully imported trades"
      else
        flash[:alert] = "error importing trades"
      end

      redirect_to moderators_path
    end


    def add_trade
      user = User.find_or_create_by_username(user_params[:username])
      other_user = User.find_or_create_by_username(other_user_params[:username])

      trade = Trade.new(trade_params)
      trade.participants.build(participant_params.merge(user: user))
      trade.participants.build(other_participant_params.merge(user: other_user))
      trade.participants.each {|p| p.accepted_at = p.moderator_approved_at = Time.now}
      trade.completed_at = Time.now

      if trade.save
        flash[:notice] = "successfully added trade"
        redirect_to trade
      else
        flash[:alert] = "error adding trade"
        redirect_to moderator_add_trade_path
      end
    end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_search.html.erb
<div class="row">
  <div class="col-sm-4">
    <%= form_tag(trades_path, method: :get) do %>
      <div class="input-group">
        <%= text_field_tag(:q, "", placeholder: "search completed trades", type: "search", class: "form-control", value: params[:q]) %>
        <span class="input-group-btn">
          <%= submit_tag("search", class: "btn btn-primary") %>
        </span>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <% if params.include? [:q] %>
    <p>search results for: <%= params[:q] %></p>
  <% end %>
</div>

app/views/trades/_trade_list.html.erb
<%- show_search = local_assigns[:show_search] || false %>

<% if trades.try(:any?) || show_search %>
  <article>
    <% if local_assigns[:type] %>
      <div class="row">
        <h2><%= type %> trades</h2>
      </div>
    <% end %>

    <% if show_search %>
      <%= render "trades/search" %>
    <% end %>

    <% if trades && !trades.empty? %>
      <div class="row">
        <ul class="trades-list">
          <% trades.each do |trade| %>
            <li>
              <%= link_to trade.participants.first.user, user_path(trade.participants.first.user) %>
              and
              <%= link_to trade.participants.second.user, user_path(trade.participants.second.user) %>:

              <%= feedback_text(trade.lowest_feedback, "positive") do %>
                <%= link_to truncate(trade.to_s, separator: ' ', length: 75), trade_path(trade) %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="row text-center">
        <%= paginate trades, param_name: pagination_param %>
      </div>
    <% elsif show_search %>
      <div class="row"><p>no search results for: <%= params[:q] %></p></div>
    <% end %>
  </article>
<% end %>

app/views/trades/index.html.erb
<% unless current_user %>
  <div class="row">
    <div class="alert alert-info">
      welcome to the <%= link_to "/r/beertrade", "http://reddit.com/r/beertrade" %> trade tracking app.  from here you can request beer trades with other reddit users.  just sign in above to get started.
    </div>
  </div>
<% end %>

<%= render "trades/trade_list", trades: @trades, type: "latest", pagination_param: :page, show_search: true %>

<%= render "users/search" %>

app/views/trades/new.html.erb
<h1>request a new beer trade</h1>

<%= form_for(@trade) do |f| %>
  <div class="reddit-username-input form-group has-feedback">
    <%= f.label :participant_username, "who are you trading with?", class: "control-label" %>
    <%= render "users/reddit_user_search" %>
  </div>

  <div id="no-trades-message" class="hidden trader-alert alert alert-info fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>caution</strong> this user has no reported feedback.  consider having the user send their end of the deal first and/or send pictures and tracking numbers.
  </div>

  <div id="neutral-trades-message" class="hidden trader-alert alert alert-warning fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>warning</strong> this user has received neutral feedback in the past.  perhaps you should <a class="trader-link" href="#">review their feedback</a> before finalizing a trade with them
  </div>

  <div id="bad-trades-message" class="hidden trader-alert alert alert-danger fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>warning</strong> this user has received bad feedback in the past.  perhaps you should <a class="trader-link" href="#">review their feedback</a> before finalizing a trade with them
  </div>


  <div class="form-group">
    <%= f.label :agreement, "what did you agree to trade?", class: "control-label" %>
    <%= f.text_field :agreement, placeholder: "(optional)", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/trades/search.html.erb
<h1>search results</h1>
  <%= render "trades/search" %>
</div>

<%= render "trades/trade_list", trades: @results, type: "latest", pagination_param: :page %>

app/views/trades/show.html.erb
<div class="row">
  <div class="trade-action-buttons pull-right">
    <% if @trade.waiting_to_give_feedback? current_user %>
      <% participant = @trade.participant(current_user) %>

      <%= link_to "update shipping info", edit_trade_participant_path(@trade, participant), class: "btn btn-primary" %>
      <%= link_to "leave feedback and complete trade", edit_trade_participant_path(@trade, participant.other_participant), class: "btn btn-primary" %>
    <% end %>

    <% if current_user.try(:moderator?) %>
      <%= link_to "delete", trade_path(@trade), method: :delete, class: "btn btn-danger", data: {confirm: "are you sure?"} %>
    <% end %>
  </div>

  <h2 class="pull-left"><%= @trade %></h2>
</div>


<% if @trade.waiting_for_approval? current_user %>
  <div class="row" id="approve-trade">
    this trade is waiting your approval:

    <%= link_to "accept", trade_participants_path(@trade), method: :post, class: "btn btn-success btn-lg" %>
    <%= link_to "decline", trade_path(@trade), method: :delete, class: "btn btn-danger btn-lg" %>
  </div>
<% end %>


<% if @trade.completed? %>
  <dl class="row">
    <% @trade.participants.each do |participant| %>
      <dt>
        <%= link_to participant.other_participant.user, user_path(participant.other_participant.user) %> said
      </dt>
      <dd>
        <%= feedback_text(participant.feedback_type) do %>
          <%= participant.feedback %>
        <% end %>
      </dd>
    <% end %>
  </dl>
<% else %>
  <h3><%= trade_status_message(@trade) %></h3>
<% end %>


<% if @trade.has_shipping_info? && (@trade.participant(current_user) || current_user.try(:moderator?)) %>
  <div class="row" id="shipping-info">
    <h3>shipping info</h3>
    <dl>
      <% @trade.participants.each do |participant| %>
        <% if participant.shipping_info? %>
          <dt><%= link_to participant.user, user_path(participant.user) %> sent</dt>
          <dd><%= link_to participant.shipping_info, shipping_info_url(participant.shipping_info) %></dd>
        <% end %>
      <% end %>
    </dl>
  </div>
<% end %>
  

<div class="row small">
  <strong>requested</strong> <%= time_ago_in_words(@trade.created_at) %> ago<% if current_user.try(:moderator?) && @trade.organizing_participant.ip_address? %>, from ip: <%= @trade.organizing_participant.ip_address %><% end %><%= "," if @trade.completed? %>

  <% if @trade.completed? %>
    <strong>completed</strong>
    <%= time_ago_in_words(@trade.completed_at) %> ago
  <% end %>
</div>