config/routes.rb
Rails.application.routes.draw do
  resources :trades, except: [:edit, :update] do
    resources :participants, only: [:create, :edit, :update]
  end

  resources :users, only: [:index, :show, :create] do
    resources :participants, only: [:index]
  end

  resources :moderators, only: [:index] 
  get 'moderators/import_trades', to: "moderators#import_trades"
  get 'moderators/change_username', to: "moderators#change_username"
  get 'moderators/add_trade', to: "moderators#add_trade"

  resources :help, only: [:index]

  resources :sessions, only: [:new, :destroy]
  get '/auth/:provider/callback', to: 'sessions#create', as: :oauth_callback

  root to: 'trades#index'
end

app/views/layouts/_flash_messages.html.erb
<div class="row">
  <% if notice %>
    <div class="alert alert-success fade in">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div class="alert alert-danger fade in">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= alert %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <ul>
    <li><%= link_to "message the moderators", "https://www.reddit.com/message/compose?to=%2Fr%2Fbeertrade&subject=&message=" %></li>
    <li><%= link_to "open source", "https://github.com/patrickomatic/beertrade" %></li>
    <li><%= link_to "help", help_index_path %></li>
  </ul>
</footer>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-69182033-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<nav class="row header-nav">
  <% if current_user %>
      <ul id="left-nav">
        <li><%= link_to 'home', root_path %></li>
        <li><%= link_to '+ request a trade', new_trade_path %></li>
      </ul>

      <ul id="right-nav">
        <li>
          <%= link_to current_user, user_path(current_user) %>

          <% notification_count = current_user.unseen_notifications_count %>
          <% if notification_count > 0 %>
            <%= link_to notification_count, user_path(current_user), title: "you have #{notification_count} unseen notifications", class: "alert alert-info unseen-notifications-count" %>
          <% end %>
        </li>

        <% if current_user.moderator? %>
          <li>
            <%= link_to "mod stuff", moderators_path %>
          </li>
        <% end %>

        <li><%= link_to "logout", session_path(current_user), method: :delete %></li>
      </ul>
  <% else %>
    <h3><%= link_to "sign in with reddit", '/auth/reddit' %></h3>
  <% end %>
</nav>

app/views/layouts/_notice.html.erb
<div id="notice">
  The new home of r/beertrade is <a href="http://rbeer.trade/r/beertrade">http://rbeer.trade/r/beertrade</a>.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>/r/beertrade trade tracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/notice" %>

    <div id="main" class="container-fluid">
      <%= render "layouts/header" %>
      <%= render "layouts/flash_messages" %>

      <%= yield %>

      <%= render "layouts/footer" %>
      <%= render "layouts/google_analytics" %>
    </div>
  </body>
</html>